@IsTest(SeeAllData = true)
public class Future_Simulation_VFPage_ApexControllerT {
  public static testMethod void testm(){
         
          
          Test.startTest();
     Future_Simulation_VFPage_ApexController t = new Future_Simulation_VFPage_ApexController();
       t.clientId = '0014600001dieTeAAI';
      t.showClientLookup=false;
      t.fadeOut=false;
          
          Test.stopTest();
}
}